### PR TITLE
Enrich event bindings example with KeyBinding

### PR DESCRIPTION
**Pull request by Evangelink**
Follow-up PR from thread #331

### CODE REVIEW

**Comment by cmeeren** [comment]
Hm, it seems that I have misunderstood. This functionality does not seem to depend on event bindings at all. If that is correct, I don't think it belongs in this sample, which specifically demonstrates event bindings using `Microsoft.Xaml.Behaviors.Wpf`. I'd like to keep it focused for that.

If keyboard shortcuts are this simple and already play nice with bindings/Elmish.WPF, do we need this in a sample at all?

**Comment by Evangelink** [comment]
It's indeed that simple and purely wpf related. I totally forgot about this wpf feature and went with a more complex approach on the model (unneedingly complex).

Feel free to close the PR if you think that does not bring anything.

**Comment by TysonMN** [comment]
> But if keyboard shortcuts are this simple and already play nice with bindings/Elmish.WPF, do we need this in a sample at all?

We don't. The reason we thought it might be useful to include this approach to keyboard shortcuts in this sample is that another way to do keyboard shortcuts is to subscribe to the `KeyDown` event.

**Comment by cmeeren** [comment]
Ok. I suggest a separate (very simple) sample dedicated to keyboard shortcuts, then. What do you think?

The sample can, for example, just display a checkbox that can be toggled with a shortcut like Ctrl-Something, together with (visible, not tooltip) text that describes that it can be toggled with this shortcut.

**Comment by TysonMN** [comment]
I want to capture this key binding knowledge, so I am merging this PR.

**Comment by Evangelink** [comment]
Sorry guys, I got really busy at work lately and a bit un-motivated at home to do some extra coding. I will try to get back to you as soon as possible.

**Comment by TysonMN** [comment]
No problem @Evangelink. We are grateful for any amount of help that your provide. :)

**Pull request merged**
