### PR TITLE
Errors observable collection (v3.5.7)

### LINKED ISSUE #362: Return errors as ObservableCollection<object>
When doing validation with https://github.com/lfr/FSharp.Domain.Validation or https://github.com/JamesRandall/AccidentalFish.FSharp.Validation you can have mo than one error per property.
UWP does not have native support of `INotifayDataErrorInfo` so that we created our control that displays errors via `ItemsControl` which prefers `ObservableCollection` as `ItemsSource`

I think that validation errors must be returned similar to `Binding.oneWaySeq` where you can set comparers and merge new errors seq into old errors and update UI (`ItemsControl`) accordingly.

### PR DESCRIPTION
**Pull request by dim-37**
Resolves #362

### CODE REVIEW

**Comment by xperiandri** [comment]
@TysonMN create a branch for v3, please.
We implemented errors as an `ObservableCollection`.
Only 1 test is broken. Could you have a look into it?

**Comment by TysonMN** [comment]
> @TysonMN create a branch for v3, please.

Done.  I also edited your PR to target that branch.

**Comment by TysonMN** [comment]
Can you share a link to a branch that uses the code in this PR?

**Comment by xperiandri** [comment]
@dim-37

**Comment by TysonMN** [comment]
That branch is the same one in this PR.  I don't think that is the right one.  I edited the OP to add "Resolves #362".  That edit is correct, right?  I am asking for a branch that uses this change but would not be able to use the code in `v3`.  The `Validation` sample in this repository does not need the change in this PR.  Based on the OP in #362, I expect such a branch to contain a UWP application.

**Comment by xperiandri** [comment]
Yes, the commits in this branch are cherry-picked from Elmish.Uno repository

**Comment by xperiandri** [comment]
It is not ready yet. @dim-37 is fixing validation sample now

**Comment by TysonMN** [comment]
As some point, can you also rebase this branch on `v3` now that it exists?

**Comment by xperiandri** [comment]
Elmish.Uno is already rebased onto 3.5.7

**Comment by xperiandri** [comment]
That is why we want to merge our changes to 3.5.7 first

**Comment by xperiandri** [comment]
Pushed https://github.com/xperiandri/Elmish.Uno/tree/navigation

Notice how animation works. Sometimes it does not work as expexted.
Have you update elmStyleMerge function in v4?

**Comment by TysonMN** [comment]
> Have you update elmStyleMerge function in v4?

No, I simply moved it in PR #259, which partially addresses #139.

**Comment by xperiandri** [comment]
Looks like in some case it works incorrectly

**Comment by TysonMN** [comment]
Ok. I will wait to review after it is working how you intend.

**Comment by dim-37** [comment]
Hi i wont to add default values to last fields in validations bindings but i can't use id function and i came to this 
``` F#
static member twoWayValidate
      (get: 'model -> 'a,
       set: 'a -> 'model -> 'msg,
       validate: 'model -> obj seq,
       ?getErrorId: 'e -> 'id,
       ?errorItemEquals: 'e -> 'e -> bool,
       ?wrapDispatch: Dispatch<'msg> -> Dispatch<'msg>)
      : string -> Binding<'model, 'msg> =
    TwoWayValidateData {
      Get = get >> box
      Set = unbox<'a> >> set
      GetErrorId = unbox<'e> >>(defaultArg getErrorId (fun (e:'e) -> e |> box :?> 'id ))>> box
      Validate = validate >> Seq.toArray
      ErrorItemEquals = fun x y -> (defaultArg errorItemEquals (=)) (unbox<'e> x) (unbox<'e> y)
      WrapDispatch = defaultArg wrapDispatch id
    } |> createBinding
``` 
Do you have any better suggestion?

**Comment by xperiandri** [comment]
@TysonMN have a look at my implementation of `ObservableCollection` update in the last commit of https://github.com/xperiandri/Elmish.Uno/tree/new_observablecollection_merge
Several tests fail, one hangs

**Comment by TysonMN** [comment]
(Sorry for the delayed response)

In that commit, you reverted to the previous quadratic-time merge algorithm, why?

**Comment by xperiandri** [comment]
Because it is simple and it produces the desired result with [collection item transitions](https://docs.microsoft.com/en-us/windows/uwp/design/motion/xaml-animation#list-item-changes)

**Comment by TysonMN** [comment]
I am not sure what you mean by "simple".  Sure, there is less code, but the end result of the whole commit is several failed tests and one hanging test.  That doesn't seem very simple to me.

I recommend changing one thing at a time.  Then you will have more information about what is wrong when a test fails or doesn't terminate.

**Comment by TysonMN** [comment]
I still think #362 is a reasonable change, but I am not willing to switch back to the slower implementation of `merge`.  For that reason and inactivity, I am closing this PR.

I expect that I will eventually change the code to address #362.  In the meantime, willing to work with others to address that issue.

**Pull request closed without merging**
