### PR TITLE
Make explicit the currently implicit type constraints

### LINKED ISSUE #139: Documentation improvements for 'id
This issue spun out of #131.  We should improve the documentation of `'id` to say how equality is computed.

Currently, equality is computed explicitly using F#'s [`(=)`](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/arithmetic-operators#summary-of-binary-comparison-operators) and implicitly using .NET's [`EqualityComparer<>.Default`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.equalitycomparer-1.default?view=netframework-4.8).

I expect only `EqualityComparer<>.Default` will still be in use by the time #137 is closed, so I recommend we wait until that happens to make any change here.

### LINKED ISSUE #151: Implement the strategy design pattern for VmBinding
Writing the code in #149 was more difficult than it would have been if we had stronger types in `ViewModel<'model, 'msg>`.  Nearly all the types in all the bindings are boxed to `obj` before they get used by library authors in `ViewModel<'model, 'msg>`.  Replacing one thing of (compile-time) type `obj` for another satisfies the compiler but would (typically) throw an exception at runtime.

I think the way forward to to have a view model type for every binding type.  For example, the view model for `SubModelSeqBinding` would be `SubModelSeqViewModel<'model, 'msg, 'bindingModel, 'bindingMsg, 'id>`.  These view models still need to expose a common set of behaviors, and there is common code that still needs somewhere to live.  Having `SubModelSeqViewModel<'model, 'msg, 'bindingModel, 'bindingMsg, 'id>` extend `ViewModel<'model, 'msg>` would help to minimize the change while also exposing the common set of methods and giving a home some common behavior.

There are many ways to group things.  I often see things grouped either syntactically or semantically.  Currently, I would describe the view model code as being grouped syntactically.  For example, all of the different cases of `updateValue` are located next to each other in the source code (within a pattern match on the binding type).  I am suggesting that we group the code semantically.  For example, `SubModelSeqViewModel<'model, 'msg, 'bindingModel, 'bindingMsg, 'id>` would implement `updateValue` and other methods like `TryGetMember` and `TrySetMember` by just having the code that is currently contained in the `SubModelSeq` cases of the respective pattern matches.

Speaking more technically, the branching currently expressed through pattern matching would be pushed "down" and performed by the runtime when it goes through the virtual method table while trying to determine which implementation to execute among the types in the resulting inheritance hierarchy.  I first encountered this idea in the Google Clean Code talk titled [Inheritance, Polymorphism, & Testing](https://www.youtube.com/watch?v=4F72VULWFvc).

This change would be invisible to users.  The main disadvantage I see is that pattern match cases that currently share an implemention would either have to repeat/duplicate the implementation or extract the behavior to some function that they all call.  However, I don't think this matters much because there are very few cases that share an implementation, and when they do, the implementations are very short.

### PR DESCRIPTION
**Pull request by bender2k14**
Resolves #139
Resolves #151 
...or will by the time I am done.

This PR is currently a draft.  I just achieved the first change to the API, so it is a good time to share my progress.

The change to the API is that the `'a` type parameter in the `Binding.oneWay` method now includes the equality constraint.

Technically I did "manually" add the equality constraint to `'a` (elsewhere), but only because not adding it where I did would cause a compile error.  So I think the goal I had of having such type constraints included via inference is still achieved in this case in spirit.

### CODE REVIEW

**Comment by bender2k14** [comment]
Now `'id` for `OneWaySeq` includes the equality constraint.

**Comment by bender2k14** [comment]
I am finished.  This PR is ready for review.

The typing is much stronger now.  In particular, equality type constraints were added to six binding types.  Also, the definition of `SubModelSelectedItemBinding<...>` no longer uses `obj` for any type parameters.  I did not foresee that improvement.

The only change to the API is the added type constraints.  Any method on `Binding` that creates one of those six binding records now includes the equality constraint as well.

I just finished coding (and need to go now), so I didn't test the samples much.  I will do that later today.  The tests pass for me and the build server.  Overall, this PR is a bit "bigger"/risker, but I was very careful to make my changes slowly and in a good order.

As always, naming can probably be improved.  I am always open to suggestions.

I left several TODO comments along the way.  They are all minor.  I was not planning on doing them in this PR, but I could if that would be better.

**Comment by cmeeren** [comment]
Thanks! I'll try to review it during the weekend. I suppose all the samples still run?

**Comment by bender2k14** [comment]
> I suppose all the samples still run?

Yes.  I just tested all of them, and everything worked correctly.  Thanks for the reminder.

**Comment by cmeeren** [comment]
I have done a very brief review (all I can prioritize right now) and it looks good. Merge when you're ready.

**Pull request merged**
