### PR TITLE
conversion to elmish 2.0

### PR DESCRIPTION
**Pull request by et1975**
using netstandard2.0 Elmish package dependency.

### CODE REVIEW

**Comment by et1975** [comment]
The good - everything builds at this point, the bad - WPF + SDK still don't play nice together and something is still borked - all the samples crash at runtime. I only tried it on small headless VM, so maybe someone else could track down the reason.

**Comment by 2sComplement** [comment]
Do the samples still work in Windows?
Also, does this invalidate #8?

**Comment by et1975** [comment]
> Do the samples still work in Windows?
see the above "samples crash" ;)

> does this invalidate #8?
Good point, I think we can still build for 4.5 if needed, but it's not in the current version of the Elmish package (461 is though).

**Comment by et1975** [comment]
Come to think, the whole NetStandard was introduced to address multi-targeting mess, so probably should just use `netstandard1.1` to target all the [compatible platforms](/dotnet/standard/blob/master/docs/versions.md) (including net45) at once.

**Comment by et1975** [comment]
No longer needed

**Comment by cmeeren** [comment]
Thanks! :)

**Comment by cmeeren** [comment]
@et1975 When converting the XAML projects to the new project format, did you manage to get them to compile from the command line? When I do `dotnet build` in a XAML project directory and have

```xml
<LanguageTargets>$(MSBuildExtensionsPath)\$(VisualStudioVersion)\Bin\Microsoft.CSharp.targets</LanguageTargets>
```
In the project file, I get the following error:

> C:\Program Files\dotnet\sdk\2.1.400\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.400\15.0\Bin\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [D:\Code\GH\Elmish.WPF\src\Samples\OneWaySeq.Views\OneWaySeq.Views.csproj]

I guess this is because `$(VisualStudioVersion)` doesn't make sense outside VS. If I instead use your version from this PR,

```xml
<LanguageTargets Condition="Exists('$(MSBuildProjectDirectory)\$(AssemblyName).csproj') AND Exists('$(MSBuildExtensionsPath)\$(VisualStudioVersion)\Bin\Microsoft.CSharp.targets')">$(MSBuildExtensionsPath)\$(VisualStudioVersion)\Bin\Microsoft.CSharp.targets</LanguageTargets>
```
then I instead get another error:

> MainWindow.xaml.cs(9,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [D:\Code\GH\Elmish.WPF\src\Samples\OneWaySeq.Views\OneWaySeq.Views.csproj]

Which I suppose is because the targets aren't included at all (since the condition fails).

Did you manage to get the XAML projects to compile from the command line / build script?

**Comment by et1975** [comment]
Yes, it compiled on my windows VM, but this looks familiar, I think you need something like [this cludge](https://github.com/AppCoreNet/DependencyInjection/blob/dev/build/netfx.props) to make sure dotnet finds the framework targets and XAML codegen kicks in.

**Comment by cmeeren** [comment]
I've had a look at that issue, but didn't understand from it how to make it compile. Also I don't know what do to with the file you linked to. I tried saving it in the project folder of one of the view projects, but it still fails with the same errors.

For now, I have excluded the samples from the build target.

**Pull request closed without merging**
