### PR TITLE
Merge master into v4

### PR DESCRIPTION
**Pull request by bender2k14**
I wanted to bring `v4` back into sync with `master`.  The main issue was minor conflicts in the `SubModelSeq` sample after PR #266 was completed.  I also updated the tutorial to match the new `SubModelSeq` code.

I tested the `SubModelSeq` sample, and everything still works.

### CODE REVIEW

**Comment by cmeeren** [comment]
Go ahead 👍

**Comment by cmeeren** [comment]
By the way, feel free to merge master into v4 anytime.

**Comment by bender2k14** [comment]
Sure.  Since there was some (minor) conflicts and some tutorial changes, I wanted to be safe and create a PR this time.

**Comment by cmeeren** [comment]
No problem. Let me know whenever there's something specific you want me to look at. I didn't look at anything in this PR.

**Comment by bender2k14** [comment]
You could look at the last two commits in this PR, which I made after I merged `master` into `v4`.  They both modify the tutorial.
- dc1a163b6a9bfeb882662145509c4d4b81e499b3  Removed a sentence about the `SubModelSeq` sample using `mapMsgWithModel` because it "only" uses `mapMsg` now
- fe66c34bd87bc170c12b2c6822e16d6bd1b8aae5  Fixed a typo by adding a missing "is"

**Comment by cmeeren** [comment]
Thanks. Looks good. 👍

**Pull request merged**
