### PR TITLE
Bug fix 102 start using elm config.measure limit ms

### LINKED ISSUE #102: ElmConfig.MeasureLimitMs not read
[`ElmConfig.MeasureLimitMs`](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/Config.fs#L11) is only written to when defining [`ElmConfig.Default`](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/Config.fs#L13-L17) (where it is set to `1`) and is _never_ read.

Currently [`measure`](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/ViewModel.fs#L117-L126) and [`measure2`](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/ViewModel.fs#L128-L137) contain the line
```
if sw.ElapsedMilliseconds > 0L then
```

Are these lines suppose to be
```
if sw.ElapsedMilliseconds > int64 config.MeasureLimitMs then
```

If so, preserving the default behavior would include initializing `ElmConfig.Default.MeasureLimitMs` to `0`.

Furthermore, it would be convenient if the type of `MeasureLimitMs` were already `int64` in order to avoid the conversion.

### PR DESCRIPTION
**Pull request by bender2k14**
Fixes #102

### CODE REVIEW

**Comment by cmeeren** [comment]
Actually, the default should be `1` and the comparison should be `>=`, not `>`. Then it fits with the property documentation. Could you do that?

**Comment by bender2k14** [comment]
Oh, sure.  Of course.  That is definitely the right comparison.  On it.

**Comment by bender2k14** [comment]
I force pushed the change

**Comment by cmeeren** [comment]
Perfect, thank you so much!

**Comment by cmeeren** [comment]
Will release shortly as v3.2.1

**Comment by bender2k14** [comment]
I am I no hurry

**Pull request merged**
