### PR TITLE
improved identifier names in the OneWaySeq case of updateValue

### PR DESCRIPTION
**Pull request by bender2k14**
I improved the names in the `OneWaySeq` case of the function `updateValue` that is the focus of #131.  All names were changed using `Ctrl+R, R` in Visual Studio.  No names were shadowing before, and no names are shadowing now.  This is a behavior preserving transformation.

### CODE REVIEW

**Comment by cmeeren** [comment]
Thanks! IIRC there are one or two other bindings with similar logic. Should those be renamed similarly, or are those different?

**Comment by bender2k14** [comment]
Sure, I can improve those names as well later today.

**Comment by bender2k14** [comment]
I just forced pushed.  The commit now includes some similar name improvements in the `SubModelSeq` case.  I decided to keep using the same PR and thus the same branch name even though its name is specific to the `OneWaySeq` case.  I can create a new branch and PR if you would prefer a better branch name to match the new contents.  I think it is fine as is though.

**Comment by cmeeren** [comment]
Thanks a lot! 👍

**Pull request merged**
