### PR TITLE
Add Bindings.mapModel

### PR DESCRIPTION
**Pull request by bender2k14**
I recently realized that `Binding<'model, 'msg>` is a ~co~ _contravariant_ functor in `'model`.  As such, there exists a function `map` with signature
```F#
('a -> 'b) -> Binding<'b, 'c> -> Binding<'a, 'c>
```
satisfying the ~co~ _contravariant_ functor laws.

This PR adds that function under the name `Binding.mapModel` (and the `list` variant as `Bindings.mapModel`) and then simplifies the boxing of a binding by making use of this new function.

The scope of both of those functions is public since I expect these could be useful to users.  (I am trying to make use of it as I clean up my Undo/Redo example https://github.com/elmish/Elmish.WPF/issues/195#issuecomment-621443558).

I tested the `SubModelSeq` sample and it still works.

(Side note: I want to define a similar function `mapMsg` under the premise that `Binding<'model, 'msg>` is a functor in `'msg`...but I don't think it is....because of `WrapDispatch` has signature `Dispatch<'msg> -> Dispatch<'msg>`.  I need to think more about this.)

### CODE REVIEW

**Comment by cmeeren** [comment]
Thanks!

1. Regarding making it public: Could you give me a use-case where it's useful for users to map the model in a binding?
2. The signature you posted
  ```f#
   ('a -> 'b) -> Binding<'b, 'c> -> Binding<'a, 'c>
   ```
   does't make sense to me. Are you sure you haven't switched `'a` and `'b` in the `Binding` types? I can't see how a function `'a -> 'b` can possibly take you from `Binding<'b, 'c>` to `Binding<'a, 'c>`.

**Comment by bender2k14** [comment]
I will separate my lengthy answers into separate comments for clarity.

Actually, I will make the scope private for now.

My goal was to first simplify the undo-redo example and then make this PR, but that hasn't happened yet.  However, I did find an internal use for this mapping function, so I thought I could contribute it for that reason.

I took Mark Seemann's workshop [From Design Patterns to universal abstractions](https://www.ndcconferences.com/slot/from-design-patterns-to-universal-abstractions) last summer (at NDC Minnesota 2019).  In brief, one of my takeaways is that abstractions motivated by mathematics are good abstractions.  So I believe that this is a good code to add even if I can't (yet!) demonstrate its usefulness to a user.

Nonetheless, what I am trying to achieve is what I think of as a lightweight alternative to a `SubModel` binding.  I could be wrong, but...if I create a `SubModel` binding, then I have to compensate in the XAML by changing the `DataContext`.  Most of the time I am ok with this, but I don't like this when I want to intersperse the bindings for what would normally be the bindings in two different submodels.  Conceptually, think of separating the F# code for a counter and its bindings from the F# code for undo-redo and its bindings while also allowing the XAML code to appear as though all that F# code was combined.

To circle back, making these two functions private is still helpful to me.  In my undo-redo work, I can just remove the private keyword, which is trivial.  Until now, I have essentially had this code in a stash that I keep applying as I try one approach, discard all my changes, try another approach, and so on.

**Comment by bender2k14** [comment]
Ah, yes.  You are right.  It is not a co-functor.  It is a contravariant functor.  That same [StackOverflow answer](https://stackoverflow.com/questions/34732571/why-there-is-no-cofunctor-typeclass-in-haskell/34732721#34732721) you linked to points out this concept at the end.

While I was an object oriented programmer, one thing I learned was [type variance](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)).  If `F<'a>` is a (covariant) functor in `'a`, then I think it is also covariant in `'a`.  Similarly, if `F<'a>` is a contravariant functor in `'a`, then I think it is also contravariant in `'a`.

For a (covariant) functor `F<'a>`, we think of it as containing or having the ability to produce or can return an instance of type `'a`.  In this case, producing a `F<'b>` from a `F<'a>` requires a function of type `a -> b`.  In contrast, a contravariant functor `F<'a>` would be thought of as having the ability to consume an instance of type `'a`.  As such, producing a `F<'b>` from a `F<'a>` requires a function of type `b -> a`.

A simple example of a contravariant functor is the function type `'a -> unit`.  Producing `'b -> unit` from `'a -> unit` requires a function of type `b -> a`.

And guess what?  [`Dispatcher<'msg>`](https://github.com/elmish/elmish/blob/12648f57092ac6c3dca383e1c25995882a646447/src/cmd.fs#L13), which is just a type alias for `'msg -> unit`, is exactly that.  `Dispatcher<'msg>` is a contravariant functor in `'msg`.

**Comment by cmeeren** [comment]
Ah, thanks. Got it now. I always think of functors as "containers" of some other type, which is obviously not a general truth.

**Comment by bender2k14** [comment]
Yes, there are two adjectives, covariant and contravariant.  For perfect clarity, exactly one would always be used.  Instead, since we almost always are talking about covariant things, we never use that adjective and instead only use contravariant when want that case.

I think the exact same problem exists in linear algebra with vectors.  There are row vectors and column vectors, but (I think) a vector without a provided adjective is meant to be a column vector.

**Comment by cmeeren** [comment]
I see. Feel free to merge when you're ready!

**Comment by bender2k14** [comment]
> Regarding making it public: Could you give me a use-case where it's useful for users to map the model in a binding?

For future reference, here is an exmaple of how I would like to use `Bindings.mapModel` and `Bindings.mapMsg`.

In my program at work, we have a drawing editor screen that currently has 17 bindings.  Here are are how five of them look now.
```
fun () ->
  [ "MouseLeftButtonDown" |> Binding.cmdParam(RawDown >> RawInputMsg |> onMouseEvent)
    "MouseLeftButtonUp" |> Binding.cmdParam(RawUp >> RawInputMsg |> onMouseEvent)
    "MouseMove" |> Binding.cmdParam(RawMove >> RawInputMsg |> onMouseEvent)
    "Undo" |> Binding.cmdIf(Undo |> UndoRedoMsg, (fun m -> m.Core) >> canUndo)
    "Redo" |> Binding.cmdIf(Redo |> UndoRedoMsg, (fun m -> m.Core) >> canRedo)
  ]
```

Here is how I could simplify them with `Bindings.mapModel` and `Bindings.mapMsg`:
```
fun () ->
  [ "MouseLeftButtonDown" |> Binding.cmdParam(RawDown |> onMouseEvent)
    "MouseLeftButtonUp" |> Binding.cmdParam(RawUp |> onMouseEvent)
    "MouseMove" |> Binding.cmdParam(RawMove |> onMouseEvent)
  ] |> Bindings.mapMsg RawInputMsg
  @
  [ "Undo" |> Binding.cmdIf(Undo, canUndo)
    "Redo" |> Binding.cmdIf(Redo, canRedo)
  ] |> Bindings.mapMsg UndoRedoMsg |> Bindings.mapModel (fun m -> m.Core)
```

Even though reasonable people could probably disagree about which of these two is "better", I still think this is a decedent example of how `Bindings.mapModel` and `Bindings.mapMsg` could be used by a user.

**Comment by cmeeren** [comment]
Thanks for the example. Personally I think the former is easier to read and understand. Also, I'd guess that most cases where it's relevant to map messages would be the sub-model bindings, where this is already built in.

**Comment by bender2k14** [comment]
Indeed, these mappings are built in with the `SubModel` binding.

I could be wrong, but I think using two `SubModel` bindings means that bindings within each sub-model must either
1. satisfy the constraint of being in sub-trees of the XAML with different settings for `DataContext` (bound to their respective sub-models) or
2. be more complex by being in a sub-tree of the XAML with the `DataContext` bound to a parent sub-model and then have more complicated XAML binding expressions that also include the mappings that could otherwise have been applied to the binding in F# via `Binding.mapModel`.

Most of the time, it is not an issue satisfying the constraint (1), so I go with that option.  On the other hand, I haven't even looked into how to express the XAML bindings in the more complicated case (2) because I don't want to push any complexity into the XAML.  And even though I think it is probably possible to express a "`mapModel`" mapping in the XAML, I doubt that it is possible to express a "`mapMsg`" mapping in the XAML.

**Pull request merged**
